<?php

namespace AppBundle\Repository;

/**
 * MeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MeRepository extends \Doctrine\ORM\EntityRepository
{
}
