security:
    encoders:
        AppBundle\Entity\User: bcrypt

    providers:
        in_memory:
            memory: ~

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            anonymous: ~
            form_login:
                login_path: admin_login
                check_path: admin_login