app_homepage:
    path:     /
    defaults: { _controller: AppBundle:Main:index }

app_legales:
    path:     /mentions-legales
    defaults: { _controller: AppBundle:Main:legales }

app_plan:
    path:     /plan-du-site
    defaults: { _controller: AppBundle:Main:plan }